[versions]
junit = "4.13.2"
itext = "2.1.7"
jdepend = "2.9.1"
flatlaf = "3.6"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
itext = { module = "com.lowagie:itext", version.ref = "itext" }
jdepend = { module = "jdepend:jdepend", version.ref = "jdepend" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
flatlafExtras = { module = "com.formdev:flatlaf-extras", version.ref = "flatlaf" }
